// SplendidCRM/React/src/views/ReloadView.tsx
/*
 * Copyright (C) 2005-2023 SplendidCRM Software, Inc. All rights reserved.
 *
 * Any use of the contents of this file are subject to the SplendidCRM Professional Source Code License 
 * Agreement, or other written agreement between you and SplendidCRM ("License"). By installing or 
 * using this file, you have unconditionally agreed to the terms and conditions of the License, 
 * including but not limited to restrictions on the number of users therein, and you may not use this 
 * file except in compliance with the License. 
 * 
 */

// 1. React and fabric. 
import * as React from 'react';
import { RouteComponentProps, withRouter, Navigate } from '../Router5'    ;
import { FontAwesomeIcon }                 from '@fortawesome/react-fontawesome';
// 2. Store and Types. 
// 3. Scripts. 
import Sql                                 from '../scripts/Sql'                ;
import Credentials                         from '../scripts/Credentials'        ;
import SplendidCache                       from '../scripts/SplendidCache'      ;
import { SplendidUI_Init }                 from '../scripts/SplendidInitUI'     ;
import { StartsWith }                      from '../scripts/utility'            ;
import { Crm_Config }                      from '../scripts/Crm'                ;
// 4. Components and Views. 
import MainContent                                   from '../ThemeComponents/MainContent';

interface IReloadViewProps extends RouteComponentProps<any>
{
}

interface IReloadViewState
{
	sRedirectUrl: string | null;
}

class ReloadView extends React.Component<IReloadViewProps, IReloadViewState>
{
	private timerID = null;
	private sRedirectUrl: string = '';
	private resetCount = 0;

	constructor(props: IReloadViewProps)
	{
		super(props);
		this.state =
		{
			sRedirectUrl: null
		};
	}

	async componentDidMount()
	{
		const { history, location } = this.props;
		//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount', location.pathname + location.search);
		// 06/25/2019 Paul.  Remove the /Reload and continue along the path. 
		if ( location.pathname.length >= 7 )
		{
			// 10/11/2019 Paul.  Include the query parameters. 
			this.sRedirectUrl = location.pathname.substring(7) + location.search;
			if ( Credentials.bMOBILE_CLIENT )
			{
				if ( StartsWith(this.sRedirectUrl, '/android_asset/www') )
				{
					this.sRedirectUrl = this.sRedirectUrl.substring(18);
				}
				if ( this.sRedirectUrl == '/index.html' )
				{
					this.sRedirectUrl = '';
				}
			}
		}
		if ( this.sRedirectUrl == '' )
		{
			this.sRedirectUrl = '/Home';
		}
		if ( SplendidCache.IsInitialized )
		{
			// 08/05/2019 Paul.  Try and replace the /Reset so that the back button will work properly. 
			// 01/21/2024 Paul.  Reset not actually being followed. 
			history.replace(this.sRedirectUrl);
			// 02/02/2024 Paul.  Navigate component seems to work. 
			this.setState({ sRedirectUrl: this.sRedirectUrl });
		}
		else
		{
			//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount Start', location.pathname);
			//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount sRedirectUrl', this.sRedirectUrl);
			let status = await SplendidUI_Init('ReloadView ' + this.sRedirectUrl);
			//SplendidCache.VerifyReactState();
			if ( status )
			{
				//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount Done', this.sRedirectUrl);
				//let status = await IsAuthenticated('ReloadView.componentDidMount');
				//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount IsAuthenticated', status);
				// 06/28/2019 Paul.  Still having an issue whereby terminology is not fully loaded before we redirect.  Try to bounce through reset. 
				// 08/05/2019 Paul.  Try and replace the /Reset so that the back button will work properly. 
				// 11/03/2021 Paul.  It is not worth the effort to try to run the Admin Wizard, so keep that code in ASP.Net code. 
				//if ( Security.IS_ADMIN() && Sql.IsEmptyString(Crm_Config.ToString("Configurator.LastRun")) )
				//{
				//	history.replace('/Administration/Configurator');
				//}
				//else
				// 11/03/2021 Paul.  Do run the User Wizard if a new user. 
				if ( Sql.IsEmptyString(Credentials.sORIGINAL_TIMEZONE_ID) && !Crm_Config.ToBoolean("disableUserWizard") )
				{
					history.replace('/Users/Wizard');
					// 02/02/2024 Paul.  Navigate component seems to work. 
					this.setState({ sRedirectUrl: '/Users/Wizard' });
				}
				else
				{
					history.replace('/Reset' + this.sRedirectUrl);
					// 02/02/2024 Paul.  Navigate component seems to work. 
					this.setState({ sRedirectUrl: '/Reset' + this.sRedirectUrl });
				}
			}
			else
			{
				//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.componentDidMount Init returned not ready, auto-reset in 5 seconds');
				// 01/21/2020 Paul.  Give it 5 more seconds. 
				// 10/31/2021 Paul.  Reduce to 1 second, but repeat 5 times. 
				this.resetCount = 0;
				this.timerID = setInterval(this.ResetTimer, 1000);
			}
		}
	}

	componentWillUnmount()
	{
		if ( this.timerID != null )
		{
			clearInterval(this.timerID);
		}
	}

	ResetTimer = () =>
	{
		const { history } = this.props;
		this.resetCount++;
		// 10/31/2021 Paul.  Reduce to 1 second, but repeat 5 times. 
		//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.ReseTimer', this.resetCount, SplendidCache.IsInitialized);
		if ( this.resetCount >= 5 || SplendidCache.IsInitialized )
		{
			clearInterval(this.timerID);
			this.timerID = null;
			//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.ReseTimer sORIGINAL_TIMEZONE_ID', Credentials.sORIGINAL_TIMEZONE_ID);
			// 11/03/2021 Paul.  It is not worth the effort to try to run the Admin Wizard, so keep that code in ASP.Net code. 
			//if ( SplendidCache.IsInitialized && Security.IS_ADMIN() && Sql.IsEmptyString(Crm_Config.ToString("Configurator.LastRun")) )
			//{
			//	history.replace('/Administration/Configurator');
			//}
			//else
			// 11/03/2021 Paul.  Do run the User Wizard if a new user. 
			if ( SplendidCache.IsInitialized && Sql.IsEmptyString(Credentials.sORIGINAL_TIMEZONE_ID) && !Crm_Config.ToBoolean("disableUserWizard") )
			{
				history.replace('/Users/Wizard');
				// 02/02/2024 Paul.  Navigate component seems to work. 
				this.setState({ sRedirectUrl: '/Users/Wizard' });
			}
			else
			{
				history.replace('/Reset' + this.sRedirectUrl);
				// 02/02/2024 Paul.  Navigate component seems to work. 
				this.setState({ sRedirectUrl: '/Reset' + this.sRedirectUrl });
			}
		}
	}

	public render()
	{
		const { location } = this.props;
		//console.log((new Date()).toISOString() + ' ' + this.constructor.name + '.render', location.pathname);

		return (<MainContent>
			<div id={ this.constructor.name + '_spinner' } style={ {textAlign: 'center'} }>
				<FontAwesomeIcon icon="spinner" spin={ true } size="5x" />
				{ this.state.sRedirectUrl
				? <Navigate to={ this.state.sRedirectUrl } replace={ true } />
				: null
				}
			</div>
		</MainContent>);
	}
}

export default withRouter(ReloadView);

// SplendidCRM/Angular/src/app/views/ReloadView.ts
import { Component, OnInit, OnDestroy        } from '@angular/core'                         ;
import { Router                              } from '@angular/router'                       ;
import { faSpinner                           } from '@fortawesome/free-solid-svg-icons'     ;

import { ApplicationService                  } from '../scripts/Application'                ;
import { SplendidCacheService                } from '../scripts/SplendidCache'              ;
import { CredentialsService                  } from '../scripts/Credentials'                ;
import { CrmConfigService                    } from '../scripts/Crm'                        ;
import { StartsWith                          } from '../scripts/utility'                    ;
import Sql                                     from '../scripts/Sql'                        ;

@Component({
	selector: 'ReloadView',
	template: `<div style="text-align: center">
			<fa-icon [icon]="spinner" size='5x' [spin]="true"></fa-icon>
		</div>`,
})
export class ReloadViewComponent implements OnInit
{
	public  spinner     = faSpinner;
	private timerID     : any    = null;
	private sRedirectUrl: string = '';
	private resetCount  : number = 0;

	constructor(private router: Router, private Application: ApplicationService, private SplendidCache: SplendidCacheService, private Credentials: CredentialsService, private Crm_Config: CrmConfigService)
	{
		//console.log(this.constructor.name + '.constructor');
	}

	async ngOnInit(): Promise<void>
	{
		console.log(this.constructor.name + '.componentDidMount', location.pathname + location.search);
		// 06/25/2019 Paul.  Remove the /Reload and continue along the path. 
		if ( location.pathname.indexOf('/Reload') >= 0 )
		{
			// 10/11/2019 Paul.  Include the query parameters.
			this.sRedirectUrl = location.pathname.split('/Reload')[1] + location.search;
			// 07/30/2022 Paul.  Base may be included in pathname, so we need to remove. 
			let sBaseUrl: string = this.Credentials.sBASE_URL;
			if ( StartsWith(this.sRedirectUrl, sBaseUrl) && sBaseUrl.length > 1 )
			{
				this.sRedirectUrl = this.sRedirectUrl.substr(sBaseUrl.length - 1);
			}
			console.log(this.constructor.name + '.componentDidMount sRedirectUrl', this.sRedirectUrl);
			if ( this.Credentials.bMOBILE_CLIENT )
			{
				if ( StartsWith(this.sRedirectUrl, '/android_asset/www') )
				{
					this.sRedirectUrl = this.sRedirectUrl.substring(18);
				}
				if ( this.sRedirectUrl == '/index.html' )
				{
					this.sRedirectUrl = '';
				}
			}
		}
		if ( this.sRedirectUrl == '' )
		{
			this.sRedirectUrl = '/Home';
		}
		if ( this.SplendidCache.IsInitialized )
		{
			this.router.navigateByUrl(this.sRedirectUrl);
		}
		else
		{
			//console.log(this.constructor.name + '.componentDidMount Start', location.pathname);
			//console.log(this.constructor.name + '.componentDidMount sRedirectUrl', this.sRedirectUrl);
			let status = await this.Application.Init('ReloadView ' + this.sRedirectUrl);
			//SplendidCache.VerifyReactState();
			if ( status )
			{
				//console.log(this.constructor.name + '.componentDidMount Done', this.sRedirectUrl);
				//let status = await IsAuthenticated('ReloadView.componentDidMount');
				//console.log(this.constructor.name + '.componentDidMount IsAuthenticated', status);
				// 06/28/2019 Paul.  Still having an issue whereby terminology is not fully loaded before we redirect.  Try to bounce through reset. 
				// 08/05/2019 Paul.  Try and replace the /Reset so that the back button will work properly. 
				// 11/03/2021 Paul.  It is not worth the effort to try to run the Admin Wizard, so keep that code in ASP.Net code. 
				//if ( Security.IS_ADMIN() && Sql.IsEmptyString(Crm_Config.ToString("Configurator.LastRun")) )
				//{
				//	this.router.navigateByUrl('/Administration/Configurator');
				//}
				//else
				// 11/03/2021 Paul.  Do run the User Wizard if a new user. 
				if ( Sql.IsEmptyString(this.Credentials.sORIGINAL_TIMEZONE_ID) && !this.Crm_Config.ToBoolean("disableUserWizard") )
				{
					this.router.navigateByUrl('/Users/Wizard');
				}
				else
				{
					this.router.navigateByUrl('/Reset' + this.sRedirectUrl);
				}
			}
			else
			{
				//console.log(this.constructor.name + '.componentDidMount Init returned not ready, auto-reset in 5 seconds');
				// 01/21/2020 Paul.  Give it 5 more seconds. 
				// 10/31/2021 Paul.  Reduce to 1 second, but repeat 5 times. 
				this.resetCount = 0;
				// 05/30/2022 Paul.  Must wrap timmer call to ensure proper this within. 
				this.timerID = setInterval(() =>
				{
					this.ResetTimer();
				}, 1000);
			}
		}
	}

	ngOnDestroy()
	{
		if ( this.timerID != null )
		{
			clearInterval(this.timerID);
			this.timerID = null;
		}
	}

	private ResetTimer()
	{
		try
		{
			this.resetCount++;
			// 10/31/2021 Paul.  Reduce to 1 second, but repeat 5 times. 
			//console.log(this.constructor.name + '.ReseTimer', this.resetCount, this.SplendidCache.IsInitialized);
			if ( this.resetCount >= 5 || this.SplendidCache.IsInitialized )
			{
				clearInterval(this.timerID);
				this.timerID = null;
				//console.log(this.constructor.name + '.ReseTimer sORIGINAL_TIMEZONE_ID', Credentials.sORIGINAL_TIMEZONE_ID);
				// 11/03/2021 Paul.  It is not worth the effort to try to run the Admin Wizard, so keep that code in ASP.Net code. 
				//if ( SplendidCache.IsInitialized && Security.IS_ADMIN() && Sql.IsEmptyString(Crm_Config.ToString("Configurator.LastRun")) )
				//{
				//	this.router.navigateByUrl('/Administration/Configurator');
				//}
				//else
				// 11/03/2021 Paul.  Do run the User Wizard if a new user. 
				if ( this.SplendidCache.IsInitialized && Sql.IsEmptyString(this.Credentials.sORIGINAL_TIMEZONE_ID) && !this.Crm_Config.ToBoolean("disableUserWizard") )
				{
					this.router.navigateByUrl('/Users/Wizard');
				}
				else
				{
					this.router.navigateByUrl('/Reset' + this.sRedirectUrl);
				}
			}
		}
		catch(error: any)
		{
			console.error(this.constructor.name + '.ResetTimer', error);
		}
	}

}
